name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag openjdk:latest
        docker tag openjdk:latest registry.cn-hangzhou.aliyuncs.com/code4thought/openjdk:ffmpeg
        docker login --username=openjdk@1039415177396567 --password=${{ secrets.ALIYUN_ACCESS_KEY }} registry.cn-hangzhou.aliyuncs.com
        docker push registry.cn-hangzhou.aliyuncs.com/code4thought/openjdk:ffmpeg
